### PR TITLE
Add configurable display relative date in alert list

### LINKED ISSUE #135: Relative time
Would be nice to see dates in relative format, such "10 sec ago".
Should I use [urish/angular-moment](https://github.com/urish/angular-moment) or [wildlyinaccurate/angular-relative-date](https://github.com/wildlyinaccurate/angular-relative-date) to implement this?

### PR DESCRIPTION
**Pull request by popstas**
If dates.listRelative == true, then output date such:
Tue 13 Feb 21:11 (5 minutes ago)

Closes #135

### CODE REVIEW

**Comment by satterly** [comment]
I've been reluctant to merge this because the alert list can be really long for some people which forces text boxes to wrap and make fewer alerts visible in a single screen. So making the date column twice as long is not something I would be keen on. Is it necessary for this to be visible or could it be hidden until someone hovers over the date with a mouse and this it would show in a hover box?

**Comment by satterly** [comment]
See GitHub as an example...

screen shot 2018-07-26 at 22 59 26

**Comment by popstas** [comment]
By default dates display don't changes, so people with long lists will not affected.

**Comment by satterly** [comment]
After checking this out and fixing a merge conflict and a bug I got this working so that I could see for myself how this looked. (You should normally include a screenshot in a PR for a UI change to help the reviewer).

screen shot 2018-07-27 at 10 10 14

I have to say I don't like it. I don't think it reduces readability of the alert list and doesn't add much value as it's meant to be a summary view with drill-down for more detailed info. If you want to redo this so that it shows the relative date on hover then I will reconsider. For now though, it's a "no". Sorry.

Thanks for your contribution and please don't be discouraged from contributing again in the future.

**Pull request closed without merging**
